### ISSUE TITLE
Overwrite `/Data` directory files

### ISSUE THREAD

**Issue by EdenCoder** [Didstopia/7dtd-server#14]
I want to enable some of the logic in `items.xml`; however restarting the server causes `/Data` to be overwritten.

Thanks in advance

**Comment by Dids** [comment]
Can you elaborate a bit more? What's the full path to `items.xml`?

**Comment by groutc** [comment]
@Dids If I had to guess he's talking about 7dtd-server/7dtd_data/Data/items.xml. Does the steamcmd verification overwrite this file before the game is launched because it detects that items.xml was modified?

**Comment by Dids** [comment]
Hmm, not sure, but if it does, I'd consider that a bug with the game server itself, because if it's a file that's meant to be edited, validation shouldn't touch those.

As a temporary solution, you could run it with `SEVEN_DAYS_TO_DIE_START_MODE=2`, which would skip automatic update (and validation).
