### ISSUE TITLE
Unable to specify beta branch

### ISSUE THREAD

**Issue by arvalaan** [Didstopia/7dtd-server#23]

**Comment by vinanrra** [comment]
+1

**Comment by vinanrra** [comment]
You can edit:

install.txt

```
@sSteamCmdForcePlatformType linux
login anonymous
force_install_dir /steamcmd/7dtd
app_update 294420 -beta latest_experimental validate
quit
```

and link with docker-compose to a local file


Edit1:

You will get this error:

7days   | [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
7days   | dlopen failed trying to load:
7days   | steamclient.so
7days   | with error:
7days   | steamclient.so: cannot open shared object file: No such file or directory
7days   | [S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
7days   | 2019-10-17T22:29:26 44.216 ERR [Steamworks.NET] Could not initialize GameServer
7days   | 2019-10-17T22:29:30 47.909 INF Calculating hashes took 4572 ms (world size 683 MiB)

Because of this:

7days   | Unable to preload the following plugins:
7days   |       libMouseLib.so
7days   |       libeac_server.so
7days   |       libeasyanticheat.so
7days   |       libgetrss.so
7days   |       libsteam_api.so
7days   |       steamclient.so
7days   |       libMouseLib.so


Full log:

https://pastebin.com/JUjchPGq

**Comment by vinanrra** [comment]
Full log:

https://pastebin.com/JUjchPGq

**Comment by MandalorePatriot** [comment]
I'm having this same issue as well, tried to update SEVEN_DAYS_TO_DIE_UPDATE_BRANCH to latest_experimental but it did not update.

This really needs to be an option for the docker.

**Comment by vinanrra** [comment]
@arvalaan @MandalorePatriot 

I created my own Docker image, if you want to use it here its the github and DockerHub

https://github.com/vinanrra/Docker-7DaysToDie

https://hub.docker.com/r/vinanrra/7dtd-server

**Comment by Dids** [comment]
Several issues, including this one, have been fixed with the latest release.

The latest release replaces `SEVEN_DAYS_TO_DIE_UPDATE_BRANCH` with `SEVEN_DAYS_TO_DIE_BRANCH`, and setting this to `latest_experimental ` would use that branch, and it'll also automatically add `-beta` if necessary.

Other fixes include the `steamclient.so not found` error, as well as minor improvements to the graceful shutdown logic.
